# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ParkIt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ParkIt
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Functions'
  pod 'Firebase/Auth'

  target 'ParkItTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ParkItUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
